/**
 * Lista de países para el signup de booker.
 *  - `es`: nombre para mostrar (audiencia chilena → español).
 *  - `api`: nombre en inglés que espera la API de ciudades
 *    (countriesnow.space, ver fetchCities). Debe matchear o las ciudades
 *    no cargan (degrada a texto libre, no rompe el signup).
 * Orden: Chile + Latam primero (mercado núcleo), resto alfabético.
 */
export interface Country {
  es: string;
  api: string;
}

export const DEFAULT_COUNTRY = "Chile";

export const COUNTRIES: Country[] = [
  // — Núcleo: Chile + Latam —
  { es: "Chile", api: "Chile" },
  { es: "Argentina", api: "Argentina" },
  { es: "Bolivia", api: "Bolivia" },
  { es: "Brasil", api: "Brazil" },
  { es: "Colombia", api: "Colombia" },
  { es: "Costa Rica", api: "Costa Rica" },
  { es: "Cuba", api: "Cuba" },
  { es: "Ecuador", api: "Ecuador" },
  { es: "El Salvador", api: "El Salvador" },
  { es: "Guatemala", api: "Guatemala" },
  { es: "Honduras", api: "Honduras" },
  { es: "México", api: "Mexico" },
  { es: "Nicaragua", api: "Nicaragua" },
  { es: "Panamá", api: "Panama" },
  { es: "Paraguay", api: "Paraguay" },
  { es: "Perú", api: "Peru" },
  { es: "Puerto Rico", api: "Puerto Rico" },
  { es: "República Dominicana", api: "Dominican Republic" },
  { es: "Uruguay", api: "Uruguay" },
  { es: "Venezuela", api: "Venezuela" },
  // — Resto del mundo (alfabético) —
  { es: "Afganistán", api: "Afghanistan" },
  { es: "Albania", api: "Albania" },
  { es: "Alemania", api: "Germany" },
  { es: "Andorra", api: "Andorra" },
  { es: "Angola", api: "Angola" },
  { es: "Arabia Saudita", api: "Saudi Arabia" },
  { es: "Argelia", api: "Algeria" },
  { es: "Armenia", api: "Armenia" },
  { es: "Australia", api: "Australia" },
  { es: "Austria", api: "Austria" },
  { es: "Azerbaiyán", api: "Azerbaijan" },
  { es: "Bahamas", api: "Bahamas" },
  { es: "Bangladés", api: "Bangladesh" },
  { es: "Baréin", api: "Bahrain" },
  { es: "Bélgica", api: "Belgium" },
  { es: "Belice", api: "Belize" },
  { es: "Benín", api: "Benin" },
  { es: "Bielorrusia", api: "Belarus" },
  { es: "Birmania (Myanmar)", api: "Myanmar" },
  { es: "Bosnia y Herzegovina", api: "Bosnia and Herzegovina" },
  { es: "Botsuana", api: "Botswana" },
  { es: "Brunéi", api: "Brunei" },
  { es: "Bulgaria", api: "Bulgaria" },
  { es: "Burkina Faso", api: "Burkina Faso" },
  { es: "Burundi", api: "Burundi" },
  { es: "Bután", api: "Bhutan" },
  { es: "Cabo Verde", api: "Cape Verde" },
  { es: "Camboya", api: "Cambodia" },
  { es: "Camerún", api: "Cameroon" },
  { es: "Canadá", api: "Canada" },
  { es: "Catar", api: "Qatar" },
  { es: "Chad", api: "Chad" },
  { es: "China", api: "China" },
  { es: "Chipre", api: "Cyprus" },
  { es: "Ciudad del Vaticano", api: "Vatican City" },
  { es: "Comoras", api: "Comoros" },
  { es: "Congo", api: "Congo" },
  { es: "Congo (RD)", api: "Democratic Republic of the Congo" },
  { es: "Corea del Norte", api: "North Korea" },
  { es: "Corea del Sur", api: "South Korea" },
  { es: "Costa de Marfil", api: "Ivory Coast" },
  { es: "Croacia", api: "Croatia" },
  { es: "Dinamarca", api: "Denmark" },
  { es: "Dominica", api: "Dominica" },
  { es: "Egipto", api: "Egypt" },
  { es: "Emiratos Árabes Unidos", api: "United Arab Emirates" },
  { es: "Eritrea", api: "Eritrea" },
  { es: "Eslovaquia", api: "Slovakia" },
  { es: "Eslovenia", api: "Slovenia" },
  { es: "España", api: "Spain" },
  { es: "Estados Unidos", api: "United States" },
  { es: "Estonia", api: "Estonia" },
  { es: "Etiopía", api: "Ethiopia" },
  { es: "Filipinas", api: "Philippines" },
  { es: "Finlandia", api: "Finland" },
  { es: "Fiyi", api: "Fiji" },
  { es: "Francia", api: "France" },
  { es: "Gabón", api: "Gabon" },
  { es: "Gambia", api: "Gambia" },
  { es: "Georgia", api: "Georgia" },
  { es: "Ghana", api: "Ghana" },
  { es: "Granada", api: "Grenada" },
  { es: "Grecia", api: "Greece" },
  { es: "Guinea", api: "Guinea" },
  { es: "Guinea-Bisáu", api: "Guinea-Bissau" },
  { es: "Guinea Ecuatorial", api: "Equatorial Guinea" },
  { es: "Guyana", api: "Guyana" },
  { es: "Haití", api: "Haiti" },
  { es: "Hungría", api: "Hungary" },
  { es: "India", api: "India" },
  { es: "Indonesia", api: "Indonesia" },
  { es: "Irak", api: "Iraq" },
  { es: "Irán", api: "Iran" },
  { es: "Irlanda", api: "Ireland" },
  { es: "Islandia", api: "Iceland" },
  { es: "Islas Marshall", api: "Marshall Islands" },
  { es: "Islas Salomón", api: "Solomon Islands" },
  { es: "Israel", api: "Israel" },
  { es: "Italia", api: "Italy" },
  { es: "Jamaica", api: "Jamaica" },
  { es: "Japón", api: "Japan" },
  { es: "Jordania", api: "Jordan" },
  { es: "Kazajistán", api: "Kazakhstan" },
  { es: "Kenia", api: "Kenya" },
  { es: "Kirguistán", api: "Kyrgyzstan" },
  { es: "Kiribati", api: "Kiribati" },
  { es: "Kuwait", api: "Kuwait" },
  { es: "Laos", api: "Laos" },
  { es: "Lesoto", api: "Lesotho" },
  { es: "Letonia", api: "Latvia" },
  { es: "Líbano", api: "Lebanon" },
  { es: "Liberia", api: "Liberia" },
  { es: "Libia", api: "Libya" },
  { es: "Liechtenstein", api: "Liechtenstein" },
  { es: "Lituania", api: "Lithuania" },
  { es: "Luxemburgo", api: "Luxembourg" },
  { es: "Macedonia del Norte", api: "North Macedonia" },
  { es: "Madagascar", api: "Madagascar" },
  { es: "Malasia", api: "Malaysia" },
  { es: "Malaui", api: "Malawi" },
  { es: "Maldivas", api: "Maldives" },
  { es: "Malí", api: "Mali" },
  { es: "Malta", api: "Malta" },
  { es: "Marruecos", api: "Morocco" },
  { es: "Mauricio", api: "Mauritius" },
  { es: "Mauritania", api: "Mauritania" },
  { es: "Micronesia", api: "Micronesia" },
  { es: "Moldavia", api: "Moldova" },
  { es: "Mónaco", api: "Monaco" },
  { es: "Mongolia", api: "Mongolia" },
  { es: "Montenegro", api: "Montenegro" },
  { es: "Mozambique", api: "Mozambique" },
  { es: "Namibia", api: "Namibia" },
  { es: "Nauru", api: "Nauru" },
  { es: "Nepal", api: "Nepal" },
  { es: "Níger", api: "Niger" },
  { es: "Nigeria", api: "Nigeria" },
  { es: "Noruega", api: "Norway" },
  { es: "Nueva Zelanda", api: "New Zealand" },
  { es: "Omán", api: "Oman" },
  { es: "Países Bajos", api: "Netherlands" },
  { es: "Pakistán", api: "Pakistan" },
  { es: "Palaos", api: "Palau" },
  { es: "Palestina", api: "Palestine" },
  { es: "Papúa Nueva Guinea", api: "Papua New Guinea" },
  { es: "Polonia", api: "Poland" },
  { es: "Portugal", api: "Portugal" },
  { es: "Reino Unido", api: "United Kingdom" },
  { es: "República Centroafricana", api: "Central African Republic" },
  { es: "República Checa", api: "Czech Republic" },
  { es: "Ruanda", api: "Rwanda" },
  { es: "Rumania", api: "Romania" },
  { es: "Rusia", api: "Russia" },
  { es: "Samoa", api: "Samoa" },
  { es: "San Cristóbal y Nieves", api: "Saint Kitts and Nevis" },
  { es: "San Marino", api: "San Marino" },
  { es: "San Vicente y las Granadinas", api: "Saint Vincent and the Grenadines" },
  { es: "Santa Lucía", api: "Saint Lucia" },
  { es: "Santo Tomé y Príncipe", api: "Sao Tome and Principe" },
  { es: "Senegal", api: "Senegal" },
  { es: "Serbia", api: "Serbia" },
  { es: "Seychelles", api: "Seychelles" },
  { es: "Sierra Leona", api: "Sierra Leone" },
  { es: "Singapur", api: "Singapore" },
  { es: "Siria", api: "Syria" },
  { es: "Somalia", api: "Somalia" },
  { es: "Sri Lanka", api: "Sri Lanka" },
  { es: "Suazilandia (Esuatini)", api: "Eswatini" },
  { es: "Sudáfrica", api: "South Africa" },
  { es: "Sudán", api: "Sudan" },
  { es: "Sudán del Sur", api: "South Sudan" },
  { es: "Suecia", api: "Sweden" },
  { es: "Suiza", api: "Switzerland" },
  { es: "Surinam", api: "Suriname" },
  { es: "Tailandia", api: "Thailand" },
  { es: "Tanzania", api: "Tanzania" },
  { es: "Tayikistán", api: "Tajikistan" },
  { es: "Timor Oriental", api: "Timor-Leste" },
  { es: "Togo", api: "Togo" },
  { es: "Tonga", api: "Tonga" },
  { es: "Trinidad y Tobago", api: "Trinidad and Tobago" },
  { es: "Túnez", api: "Tunisia" },
  { es: "Turkmenistán", api: "Turkmenistan" },
  { es: "Turquía", api: "Turkey" },
  { es: "Tuvalu", api: "Tuvalu" },
  { es: "Ucrania", api: "Ukraine" },
  { es: "Uganda", api: "Uganda" },
  { es: "Uzbekistán", api: "Uzbekistan" },
  { es: "Vanuatu", api: "Vanuatu" },
  { es: "Vietnam", api: "Vietnam" },
  { es: "Yemen", api: "Yemen" },
  { es: "Yibuti", api: "Djibouti" },
  { es: "Zambia", api: "Zambia" },
  { es: "Zimbabue", api: "Zimbabwe" },
];

/** Mapa es → api para resolver el nombre que espera la API de ciudades. */
export const COUNTRY_API_BY_ES: Record<string, string> = Object.fromEntries(
  COUNTRIES.map((c) => [c.es, c.api])
);

/**
 * Ciudades de un país vía countriesnow.space (gratis, sin key).
 * Devuelve [] si falla → el form degrada a ciudad de texto libre.
 */
export async function fetchCities(apiCountry: string): Promise<string[]> {
  try {
    const res = await fetch(
      "https://countriesnow.space/api/v0.1/countries/cities",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ country: apiCountry }),
      }
    );
    if (!res.ok) return [];
    const json = (await res.json()) as { error?: boolean; data?: string[] };
    if (json.error || !Array.isArray(json.data)) return [];
    // Dedup + orden alfabético.
    return Array.from(new Set(json.data)).sort((a, b) => a.localeCompare(b));
  } catch {
    return [];
  }
}
